apiVersion: v1
kind: Service
metadata:
  name: blogspot-server-service
spec:
  selector:
    app: blogspot-server
  ports:
  - port: 3010
    targetPort: 3010
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogspot-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogspot-server
  template:
    metadata:
      labels:
        app: blogspot-server
    spec:
      containers:
      - name: blogspot-server
        image: siddjuugi/medium-app:latest
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: blogspot-secret
              key: JWT_SECRET

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: blogspot-secret
              key: DATABASE_URL

        - name: CLOUDINARY_URL
          valueFrom:
            secretKeyRef:
              name: blogspot-secret
              key: CLOUDINARY_URL

        - name: CLOUDINARY_NAME
          valueFrom:
            secretKeyRef:
              name: blogspot-secret
              key: CLOUDINARY_NAME

        - name: CLOUDINARY_API
          valueFrom:
            secretKeyRef:
              name: blogspot-secret
              key: CLOUDINARY_API

        - name: CLOUDINARY_SECRET
          valueFrom:
            secretKeyRef:
              name: blogspot-secret
              key: CLOUDINARY_SECRET

        - name: PORT
          value: "3010"

        - name: NODE_ENV
          value: "production"

        ports:
        - containerPort: 3010
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
