apiVersion: v1
kind: Service
metadata:
  name: fast-chain-service
spec:
  selector:
    app: fast-chain
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-chain
  template:
    metadata:
      labels:
        app: fast-chain
    spec:
      containers:
      - name: fast-chain
        image: siddjuugi/fast-chain:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
