apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: syncstream-db
spec:
  selector:
    app: syncstream-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: syncstream-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncstream-db
  template:
    metadata:
      labels:
        app: syncstream-db
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: syncstream
            - name: POSTGRES_USER
              value: syncstream
            - name: POSTGRES_DB
              value: syncstream
            - name: POSTGRES_HOST
              value: db-service
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
