apiVersion: v1
kind: Service
metadata:
  name: syncstream-redis-service
  labels:
    app: syncstream-redis
spec:
  selector:
    app: syncstream-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncstream-redis-deployment
  labels:
    app: syncstream-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncstream-redis
  template:
    metadata:
      labels:
        app: syncstream-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
