apiVersion: v1
kind: Service
metadata:
  name: syncstream-worker-service
  labels:
    app: syncstream-worker-service
spec:
  selector:
    app: syncstream-worker-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncstream-worker-deployment
  labels:
    app: syncstream-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncstream-worker
  template:
    metadata:
      labels:
        app: syncstream-worker
    spec:
      containers:
        - name: syncstream-worker
          image: syncstream-worker-image
          env:
            - name: DATABASE_URL
              value: postgresql://syncstream:syncstream@db-service:5432/syncstream
            - name: REDIS_HOST
              value: syncstream-redis-service
            - name: CELERY_BROKER_URL
              value: redis://syncstream-redis-service:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://syncstream-redis-service:6379/1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: syncstream-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: syncstream-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: ap-south-1
            - name: AWS_REGION
              value: ap-south-1
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: syncstream-secrets
                  key: S3_BUCKET

              

