additionalArguments:
- --providers.kubernetescrd
- --entrypoints.websecure.address=:443
- --entrypoints.web.address=:80

# Enable CRDs
providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true # This enables CRD support

deployment:
  enabled: true
ingressRoute:
  dashboard:
    enabled: true
middleware:
  enabled: true

ports:
  web:
    port: 80
    expose:
      ip: []
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      ip: []
    exposedPort: 443
    protocol: TCP

service:
  type: LoadBalancer
  annotations: {}

# Enable dashboard
dashboard:
  enabled: true

# helm upgrade traefik traefik/traefik -f trafik-setup-config/traefik-values.yaml -n traefik-v2
