apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-1-ingress
  nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: test-1-service
            port:
              number: 8080
